#!/bin/bash

# Git aliases
alias gst='git status -sb'
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias ga='git add'
alias gua='git reset HEAD' # git undo add
alias gum='git reset --merge ORIG_HEAD' # git undo merge
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gcm='git commit -m'
alias gb='git branch'
alias gba='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glog='git log'
alias glogp='git log --pretty=format:"%h %s" --graph'

# Fork CMS
alias cc='cd tools && ./remove_cache && cd ..'

# Do some commands with hhvm
alias composer="hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 /usr/local/bin/composer"
alias con="hhvm app/console"
