#!/bin/bash

alias ':q'='exit'

# Git aliases
alias gst='git status -sb'
alias gl='git pull'
alias gp='git push'
alias gd='git diff'
alias ga='git add'
alias gua='git reset HEAD' # git undo add
alias gum='git reset --merge ORIG_HEAD' # git undo merge
alias gc='git commit -v'
alias gca='git commit -v -a'

# Fork CMS
alias cc='cd tools && ./remove_cache && cd ..'

# colors
alias phpunit='phpunit --colors'
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
