#!/bin/bash

# Does a recursive find and replace
frp()
{
	search=$1
	replace=$2
	extension=$3

	if [[ "$search" == "" ]] || [[ "$replace" == "" ]] || [[ "$extension" == "" ]]
	then
		echo "usage: frp <search> <replace> <extension>"
	else
		find . -type f -name "*.$extension" -exec sed -i '' -e "s/$search/$replace/g" {} +
	fi
}

# adds an entry to the hosts file (with a backup)
addhost()
{
	site=$1

	if [[ "$site" == "" ]]
	then
		echo "usage: addvhost <name>"
	else
		sudo cp /etc/hosts /etc/hosts.original
		sudo sh -c "echo \"127.0.0.1\t${site}.dev\" >> /etc/hosts"
		sudo apachectl graceful
	fi
}
