#!/bin/bash

# returns the active git branch - this is used in rewrite_prompt()
git_branch()
{
	git branch --no-color 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# creates an SSH key and uploads it to the given host
addsshkey()
{
	username=$1
	hostname=$2

	if [[ "$username" == "" ]] || [[ "$hostname" == "" ]]
	then
		echo "usage: addsshkey <username> <hostname>"
	else
		ssh $username@$hostname 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub

		tput bold; ssh -o PasswordAuthentication=no $username@$hostname true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
	fi
}

# adds an entry to the hosts file (with a backup)
addhost()
{
	site=$1

	if [[ "$site" == "" ]]
	then
		echo "usage: addvhost <name>"
	else
		sudo cp /etc/hosts /etc/hosts.original

		sudo sh -c "echo \"127.0.0.1\t${site}.dev\" >> /etc/hosts"
		sudo apachectl graceful
	fi
}

# toggles xdebug
togglexdebug()
{
	if php -i | grep -Fq 'xdebug'
	then
		# disable
		sudo sed -i -e 's/zend_extension=\/usr\/lib\/php\/extensions\/no-debug-non-zts-20090626\/xdebug.so/\;zend_extension=\/usr\/lib\/php\/extensions\/no-debug-non-zts-20090626\/xdebug.so/g' /etc/php.ini
	else
		#enable
		sudo sed -i -e 's/\;zend_extension=\/usr\/lib\/php\/extensions\/no-debug-non-zts-20090626\/xdebug.so/zend_extension=\/usr\/lib\/php\/extensions\/no-debug-non-zts-20090626\/xdebug.so/g' /etc/php.ini
	fi
	sudo apachectl restart
}

# serialize
serialize()
{
	var=$1

	if [[ "$var" == "" ]]
	then
		echo "usage: serialize <variable>"
	else
		output=`php -r "echo serialize($1);"`
		echo -n $output | pbcopy
		echo $output
	fi
}