#!/bin/bash

# Make sure we can open up enough resources
ulimit -n 1000

# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";

# don't put duplicate lines in the history
export HISTCONTROL=ignoredups

# let the history ignore the following commands
export HISTIGNORE="ls:ll:la:pwd:clear:h:j"

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# Make ls & grep pretty
export CLICOLOR=1
export GREP_OPTIONS='--color=auto'

# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# use neovim as default editor
export EDITOR=nvim

tabs -4

########################################################################
# PATH
########################################################################

# list the directories we want to add to the PATH variable, if they exist.
paths_to_add=(
  $(brew --prefix)/bin
  "$HOME/.composer/vendor/bin"
  /usr/local/php5/bin
  "$HOME/bin"
  # MySQL
  /usr/local/mysql/bin
  # Homebrew
  /usr/local/{,s}bin
  # System
  /{,s}bin
  /usr/{,s}bin
  # Git
  /usr/local/git/bin
  # .bash folder
  "$HOME/.bash"
  # Others
  /opt/local/bin
  /opt/local/sbin
  # Pear
  /Users/woutersioen/pear/bin
);

# Now implode everything into the new PATH variable.
printf -v PATH "%s:" "${paths_to_add[@]}";
export PATH="${PATH%:}";

. `brew --prefix`/etc/profile.d/z.sh
